### ISSUE TITLE
New entrypoint usage

### ISSUE THREAD

**Issue by asamofal** [bitnami/bitnami-docker-percona-xtrabackup#2]
Hi, first of all thanks for the great image!

Previously _(`8.0.23-16-debian-10-r66 release` and early)_ the image was using some sh scripts for `ENTRYPONT` and `CMD`:
```
ENTRYPOINT [ "/entrypoint.sh" ]
CMD [ "/run.sh" ]
```
With that approach I was able to use different tools from the image _(as it's mentioned in readme)_:
```bash
docker run -it --rm --name xtrabackup bitnami/percona-xtrabackup:8.0.23-16 -- xtrabackup --version
docker run -it --rm --name xtrabackup bitnami/percona-xtrabackup:8.0.23-16 -- xbstream --version
```

My real use case was like this:
```bash
docker run -it --rm  -v $(pwd):/tmp -v %PATH_TO_MYSQL_DATA%:/var/lib/mysql bitnami/percona-xtrabackup:8.0.23-16 bash -c "xtrabackup --backup --compress --parallel=10 --compress-threads=5 --stream=xbstream --host=127.0.0.1 --user=root --password=password > /tmp/backup.xbstream"
```
I use `--stream=xbstream` option to stream backup files directly to output and in the end of the command just redirect it to `backup.xbstream` file. So in the end I just get a compressed version of backup in the single file.

But now entrypoint of the image is changed:
`ENTRYPOINT [ "xtrabackup" ]`
Now  container  handles all commands directly by `xtrabackup` tool. In case of backup creation I can't use `bash -c` in the command as well. And how  to use `xbstream` (for example) tool now?

**Comment by miguelaeh** [comment]
Hi @asamofal ,
you can use 
```
docker run -it --entrypoint xbstream --rm --name xtrabackup bitnami/percona-xtrabackup:8.0.23-16 -- --version
```

**Comment by asamofal** [comment]
@miguelaeh thanks, I've got it, now need to choose entrypoint manually if you need to call not `xtrabackup` tool.

**Comment by miguelaeh** [comment]
Hi @asamofal ,
You cannot redirect files from the host to the container without mounting a volume.

> How should I do it if now I send commands directly to xtrabackup tool inside the container?

About this, the `xtrabackup` is the current entrypoint so if you don't override the entrypoint it will be `xtrabackup`: https://github.com/bitnami/bitnami-docker-percona-xtrabackup/blob/2629de6130f8c0ac6eabb7374d76ed20a908d10a/8/debian-10/Dockerfile#L23

**Comment by asamofal** [comment]
> You cannot redirect files from the host to the container without mounting a volume.

I know. In my command above you may see that I mount a volume `-v $(pwd):/tmp` and then trying to extract a backup inside the container. But for extracting I need to use `<` sign to redirect stdin to `xbstream-extract` tool.

> About this, the xtrabackup is the current entrypoint so if you don't override the entrypoint it will be xtrabackup

I understand it. But the question is: how to use `stream` option of xtrabackup tool in this case?

---
Let's try from another side: could you _(I mean bitnami team)_ update the Readme file, please. Current version contains a wrong example in `Running commands` section (because of new endpoint).
```
docker run --rm --name percona-xtrabackup bitnami/percona-xtrabackup:8.0.26-18 -- xtrabackup --version
xtrabackup: Error: unknown argument: 'xtrabackup'
```
And add an example how to use xtrabackup in [streaming mode](https://www.percona.com/doc/percona-xtrabackup/LATEST/xtrabackup_bin/backup.streaming.html), please. 
Official documentation says to use `>` and `<` signs to redirect stdout/stdin _(for streaming a backup to the file and unpack it later)_, but it's not possible until entrypoint is not overridden to `bash`. So if for `stream` mode it's required to override the entrypoint to bash, then I think it was just a wrong decision to make `xtrabackup` default entrypoint of the image.

**Comment by asamofal** [comment]
> You cannot redirect files from the host to the container without mounting a volume.

I know. In my command above you may see that I mount a volume `-v $(pwd):/tmp` and then trying to extract a backup inside the container. But for extracting I need to use `<` sign to redirect stdin to `xbstream-extract` tool.

> About this, the xtrabackup is the current entrypoint so if you don't override the entrypoint it will be xtrabackup

I understand it. But the question is: how to use `stream` option of xtrabackup tool in this case?

---
Let's try from another side: could you _(I mean bitnami team)_ update the Readme file, please. Current version contains a wrong example in `Running commands` section (because of new endpoint).
```
docker run --rm --name percona-xtrabackup bitnami/percona-xtrabackup:8.0.26-18 -- xtrabackup --version
xtrabackup: Error: unknown argument: 'xtrabackup'
```
And add an example how to use xtrabackup in [streaming mode](https://www.percona.com/doc/percona-xtrabackup/LATEST/xtrabackup_bin/backup.streaming.html), please. 
Official documentation says to use `>` and `<` signs to redirect stdout/stdin _(for streaming a backup to the file and unpack it later)_, but it's not possible until entrypoint is not overridden to `bash`. So if for `stream` mode it's required to override the entrypoint to bash, then I think it was just a wrong decision to make `xtrabackup` default entrypoint of the image.

**Comment by miguelaeh** [comment]
Hi @asamofal ,
I don't know the exact reason why it was changed, it was 2 months ago checking the commits.
In any case, you can always create your custom image using `FROM` this image to override the entrypoint

**Comment by asamofal** [comment]
I've got the point.
